#! /bin/bash

echo "Trello-scripts: Starting..."

dir=$(dirname $0)
package=$(pip list)

if [[ "$package" == *"pipenv"* ]]; then
    echo "Trello-scripts: Pipenv is installed"
else
    echo "Trello-scripts: Pipenv is not installed"
    echo "Trello-scripts: Installing Pipenv..."
    pip install pipenv

fi
cd $dir
source $(pipenv --venv)/bin/activate
pipenv sync

rm $dir/secret/sheet_token.json

python $dir/main.py

echo "Trello-scripts: Finished."
