#! /bin/bash

echo "Trello-scripts: Starting..."
package=$(pip3 list)

if [[ "$package" == *"pipenv"* ]]; then
    echo "Trello-scripts: Pipenv is installed"
else
    echo "Trello-scripts: Pipenv is not installed"
    echo "Trello-scripts: Installing Pipenv..."
    sudo pip3 install pipenv
    pipenv install
fi
source $(pipenv --venv)/bin/activate
python main.py

echo "Trello-scripts: Finished."
